export const albums = {
  kPopAlbums: [
    {
      artist: "Twice",
      album: "Formula of Love: O+T=<3",
      best: "CRUEL",
      worst: "HELLO (NAYEON, MOMO, CHAEYONG)",
      fave: "SCIENTIST",
      albumArtLink: "/album-art/k-pop/Twice-Formula_of_Love.png",
    },
    {
      artist: "Twice",
      album: "Feel Special",
      best: "Breakthrough (Korean Version)",
      worst: "21:29",
      fave: "Feel Special",
      albumArtLink: "/album-art/k-pop/Twice-FeelSpecial.png",
    },

    {
      artist: "BTS",
      album: "Proof",
      best: "Boy With Luv",
      worst: "BTS Cypher Pt.3: Killer",
      fave: "RUN BTS",
      albumArtLink: "/album-art/k-pop/BTS-Proof.jpeg",
    },
    {
      artist: "New Jeans",
      album: "All EP's",
      best: "OMG",
      worst: "Cookie",
      fave: "Ditto",
      albumArtLink: "/album-art/k-pop/New_Jeans.webp",
    },
    {
      artist: "Stray Kids",
      album: "ODDINARY",
      best: "MANIAC",
      worst: "FREEZE",
      fave: "CHARMER",
      albumArtLink: "/album-art/k-pop/StrayKids-Oddinary.jpeg",
    },
    {
      artist: "Seventeen",
      album: "FACE THE SUN",
      best: "HOT",
      worst: "Ash",
      fave: "Darl+ing",
      albumArtLink: "/album-art/k-pop/seventeen-face-the-sun.jpeg",
    },
    {
      artist: "Monsta X",
      album: "ALL ABOUT LUV",
      best: "WHO DO YOU LOVE? (FT. French Montana)",
      worst: "SHE'S THE ONE",
      fave: "SOMEONE'S SOMEONE",
      albumArtLink: "/album-art/k-pop/Monsta_X_-_All_About_Luv.png",
    },
    {
      artist: "Itzy",
      album: "CRAZY IN LOVE",
      best: "LOCO",
      worst: "SWIPE",
      fave: "SWIPE",
      albumArtLink: "/album-art/k-pop/Itzy–Crazy_in_Love.jpeg",
    },
    {
      artist: "BLACKPINK",
      album: "KILL THIS LOVE EP",
      best: "Don't Know What To Do",
      worst: "Kill This Love",
      fave: "DDU-DU DDU-DU - Remix",
      albumArtLink: "/album-art/k-pop/Blackpink-Kill_This_Love.png",
    },
    {
      artist: "LE SSERAFIM",
      album: "All EP's",
      best: "FEARLESS",
      worst: "Anti-Fragile",
      fave: "Anti-Fragile",
      albumArtLink: "/album-art/k-pop/LESSERAFIM.png",
    },
    {
      artist: "J-Hope",
      album: "Jack In the Box",
      best: "More",
      worst: "Music Box: Reflection",
      fave: "Arson",
      albumArtLink: "/album-art/k-pop/J-Hope.png",
    },
    {
      artist: "RM",
      album: "Indigo",
      best: "Closer (with Paul Blanco and Mahalia)",
      worst: "All Day (with Tablo)",
      fave: "Still Life (with Anderson .PaaK)",
      albumArtLink: "/album-art/k-pop/RM-Indigo.jpeg",
    },
  ],

  popAlbums: [
    {
      artist: "Rina Sawayama",
      album: "SAWAYAMA",
      best: "Chosen Family",
      worst: "Paradisin'",
      fave: "XS",
      albumArtLink: "/album-art/k-pop/New_Jeans.webp",
    },
    {
      artist: "SOPHIE",
      album: "OIL OF EVERY PEARL'S UN-INSIDES",
      best: "It's Okay to Cry",
      worst: "Pretending",
      fave: "Faceshopping",
      albumArtLink: "/album-art/k-pop/New_Jeans.webp",
    },
    {
      artist: "Fujii Kaze",
      album: "HELP EVER HURT NEVER",
      best: "Shinunoga E-Wa",
      worst: "Kazeyo",
      fave: "Nan-Nan",
      albumArtLink: "/album-art/k-pop/New_Jeans.webp",
    },
    {
      artist: "Griff",
      album: "One Foot In Front of The Other",
      best: "Black Hole",
      worst: "Remembering My Dreams",
      fave: "Shade of Yellow",
      albumArtLink: "/album-art/k-pop/New_Jeans.webp",
    },
    {
      artist: "KATIE",
      album: "LOG EP",
      best: "Love Kills",
      worst: "Better Off",
      fave: "Love Kills",
      albumArtLink: "/album-art/k-pop/New_Jeans.webp",
    },
  ],

  alternativealbums: [
    {
      artist: "HAIM",
      album: "Women In Music Pt. III",
      best: "The Steps",
      worst: "Up From A Dream",
      fave: "3AM",
      albumArtLink: "/album-art/k-pop/New_Jeans.webp",
    },
  ],

  rapAlbums: [],

  taylorSwiftAlbums: [
    {
      artist: "Taylor Swift",
      album: "Taylor Swift",
      best: "Should've Said No",
      worst: "A Perfectly Good Heart",
      fave: "Picture to Burn",
      albumArtLink: "/album-art/taylor-swift/TaylorSwift-TaylorSwift.png",
    },

    {
      artist: "Taylor Swift",
      album: "Fearless",
      best: "Fearless",
      worst: "Change",
      fave: "Tell Me Why",
      albumArtLink: "/album-art/taylor-swift/TaylorSwift-Fearless.png",
    },

    {
      artist: "Taylor Swift",
      album: "Speak Now",
      best: "Dear John",
      worst: "Long Live",
      fave: "Speak Now",
      albumArtLink: "/album-art/taylor-swift/TaylorSwift-SpeakNow.png",
    },

    {
      artist: "Taylor Swift",
      album: "Red",
      best: "Red",
      worst: "Stay Stay Stay",
      fave: "We Are Never Getting Back Together",
      albumArtLink: "/album-art/taylor-swift/TaylorSwift-Red.png",
    },

    {
      artist: "Taylor Swift",
      album: "1989",
      best: "Out of the Woods",
      worst: "Bad Blood",
      fave: "New Romantics",
      albumArtLink: "album-art/taylor-swift/TaylorSwift-1989.png",
    },

    {
      artist: "Taylor Swift",
      album: "Reputation",
      best: "Delicate",
      worst: "Look What You Made Me Do",
      fave: "Getaway Car",
      albumArtLink: "album-art/taylor-swift/TaylorSwift-reputation.png",
    },

    {
      artist: "Taylor Swift",
      album: "Lover",
      best: "The Archer",
      worst: "ME!",
      fave: "False God",
      albumArtLink: "album-art/taylor-swift/TaylorSwift-lover.png",
    },

    {
      artist: "Taylor Swift",
      album: "Folklore",
      best: "exile (feat. Bon Iver)",
      worst: "peace",
      fave: "betty",
      albumArtLink: "album-art/taylor-swift/TaylorSwift-folklore.png",
    },

    {
      artist: "Taylor Swift",
      album: "Evermore",
      best: "Champagne Problems",
      worst: "Closure",
      fave: "No Body, No Crime",
      albumArtLink: "album-art/taylor-swift/TaylorSwift-evermore.png",
    },

    {
      artist: "Taylor Swift",
      album: "Fearless (Taylor's Version)",
      best: "Hey Stephen (Taylor's Version)",
      worst: "White Horse (Taylor's Version)",
      fave: "You Belong With Me (Taylor's Version)",
      albumArtLink: "album-art/taylor-swift/TaylorSwift-FearlessTV.png",
    },

    {
      artist: "Taylor Swift",
      album: "Red (Taylor's Version)",
      best: "All Too Well (10 Minute Version) (Taylor's Version)",
      worst: "Holy Ground (Taylor's Version)",
      fave: "I Bet You Think About Me (Taylor's Version) (From the Vault)",
      albumArtLink: "/album-art/taylor-swift/TaylorSwift-RedTV.jpeg",
    },

    {
      artist: "Taylor Swift",
      album: "Midnights",
      best: "Maroon",
      worst: "Question...?",
      fave: "You're on Your Own, Kid",
      albumArtLink: "album-art/taylor-swift/TaylorSwift-midnights.png",
    },
  ],
};
